I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/script.rpy", line 30, in script call
    call chapter1
  File "game/script/chapter1.rpy", line 628, in script
    scene bg black with Fade(.5)
TypeError: Fade() missing 2 required positional arguments: 'hold_time' and 'in_time'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/script.rpy", line 30, in script call
    call chapter1
  File "game/script/chapter1.rpy", line 628, in script
    scene bg black with Fade(.5)
  File "C:\GameProjects\renpy-8.0.1-sdk\renpy\ast.py", line 1658, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "C:\GameProjects\renpy-8.0.1-sdk\renpy\exports.py", line 1653, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\GameProjects\renpy-8.0.1-sdk\renpy\display\core.py", line 2798, in do_with
    return self.interact(trans_pause=True,
  File "C:\GameProjects\renpy-8.0.1-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs) # type: ignore
  File "C:\GameProjects\renpy-8.0.1-sdk\renpy\display\core.py", line 3741, in interact_core
    trans = self.ongoing_transition[None](
TypeError: Fade() missing 2 required positional arguments: 'hold_time' and 'in_time'

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.1.22070801
There is no god in Hinterland 1.0
Thu Jul 14 18:42:54 2022
